version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
    restart: "unless-stopped"
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  express:
    container_name: express
    build:
      context: ./
    volumes:
      - ./file:/server/file
    restart: "unless-stopped"
